# permissions for end users to view backends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-viewer-role
rules:
  - apiGroups:
      - solution.feature.aero.sample.com
    resources:
      - backends
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - solution.feature.aero.sample.com
    resources:
      - backends/status
    verbs:
      - get
