---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - solution.feature.aero.sample.com
    resources:
      - backends
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - solution.feature.aero.sample.com
    resources:
      - backends/finalizers
    verbs:
      - update
  - apiGroups:
      - solution.feature.aero.sample.com
    resources:
      - backends/status
    verbs:
      - get
      - patch
      - update
