apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capability-operator.fullname" . }}
  labels:
  {{- include "capability-operator.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "capability-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "capability-operator.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.annotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "capability-operator.serviceAccountName" . }}-op-svc-acc
      securityContext:
        runAsNonRoot: true
      containers:
        - args:
            - --leader-elect
          #- --leader-election-id={{ include "capability-operator.fullname" . }}
          name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
